routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');

Route::resource('roles', 'RoleController');

Route::resource('permissions', 'PermissionController');

//Route::resource('posts', 'PostController');



Route::get('login/github', 'GithubLoginController@redirectToProvider')->name('github');
Route::get('login/github/callback', 'GithubLoginController@handleProviderCallback');

Route::get('login/facebook', 'FacebookLoginController@redirectToProvider')->name('facebook');
Route::get('login/facebook/callback', 'FacebookLoginController@handleProviderCallback');

Route::get('login/google', 'GoogleLoginController@redirectToProvider')->name('google');
Route::get('login/google/callback', 'GoogleLoginController@handleProviderCallback');


Route::group(['prefix' => 'posts'], function()
    {
        Route::get('', ['uses' => 'PostController@index'])->name('posts');
        Route::get('data', ['uses' => 'PostController@anyData'])->name('posts.data');
        Route::get('create', ['uses' => 'PostController@create'])->name('posts.create');
        Route::post('store', ['uses' => 'PostController@store'])->name('posts.store');
        Route::put('{id}', ['uses' => 'PostController@update']);
        Route::delete('{id}', ['uses' => 'PostController@delete']);

    });

Route::group(['prefix' => 'mails'], function()
    {
    	Route::get('', ['uses' => 'MailController@index'])->name('mails');
    	Route::get('compose', ['uses' => 'MailController@create'])->name('mails.compose');
        Route::post('store', ['uses' => 'MailController@store'])->name('mails.store');
        Route::get('data', ['uses' => 'MailController@anyData'])->name('mails.data');
        Route::get('delete/{id}', ['uses' => 'MailController@destroy']);
	});

resources/views/include/header.blade.php
<header class="main-header">
  <!-- Logo -->
  @include('include/logo')
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account: style can be found in dropdown.less -->
        @include('include/topRightAdmin')
      </ul>
    </div>
  </nav>
</header>

resources/views/include/leftMenu.blade.php
<ul class="sidebar-menu" data-widget="tree">
  <li class="header">MAIN NAVIGATION</li>
  <li class="active treeview">
    <a href="/">
      <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    </a>
  </li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-table"></i> <span>Articles</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="{!! route('posts') !!}"><i class="fa fa-circle-o"></i> List Articles</a></li>
      <li><a href="{!! route('posts.create') !!}"><i class="fa fa-circle-o"></i> Add Article </a></li>
    </ul>
  </li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-envelope"></i> <span>Mailbox</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="{!! route('mails') !!}"><i class="fa fa-circle-o"></i> List Mails</a></li>
      <li><a href="{!! route('mails.compose') !!}"><i class="fa fa-circle-o"></i> Compose </a></li>
    </ul>
  </li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-key"></i> <span>Roles</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="{!! route('roles.index') !!}"><i class="fa fa-circle-o"></i> List Roles</a></li>
      <li><a href="{!! route('roles.create') !!}"><i class="fa fa-circle-o"></i> Add </a></li>
    </ul>
  </li>
  <li class="treeview">
    <a href="#">
      <i class="fa fa-key"></i> <span>Permission</span>
      <span class="pull-right-container">
        <i class="fa fa-angle-left pull-right"></i>
      </span>
    </a>
    <ul class="treeview-menu">
      <li><a href="{!! route('permissions.index') !!}"><i class="fa fa-circle-o"></i> List Permissions</a></li>
      <li><a href="{!! route('permissions.create') !!}"><i class="fa fa-circle-o"></i> Add Permission</a></li>
    </ul>
  </li>
  
</ul>

resources/views/include/logo.blade.php
<a href="/" class="logo">
  <!-- mini logo for sidebar mini 50x50 pixels -->
  <span class="logo-mini"><b>A</b>L</span>
  <!-- logo for regular state and mobile devices -->
  <span class="logo-lg"><b>Admin</b>Laravel</span>
</a>

resources/views/include/socialLoginLinks.blade.php
<div class="social-auth-links text-center">
	<p>- OR -</p>
	<a href="{{ route('facebook') }}" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
	Facebook</a>
	<a href="{{ route('google') }}" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
	Google+</a>
</div>

resources/views/include/topRightAdmin.blade.php
<li class="dropdown user user-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
    <span class="hidden-xs">{{ Auth::user()->name }}</span>
  </a>
  <ul class="dropdown-menu">
    <!-- User image -->
    <li class="user-header">
      <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
      <p>
        {{ Auth::user()->name }} - @role('Admin') Admin @endrole
        <small>Member since {{Carbon\Carbon::parse(Auth::user()->created_at)->format('M, Y') }}</small>
      </p>
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a href="#" class="btn btn-default btn-flat">Profile</a>
      </div>
      <div class="pull-right">
        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">Sign out</a>
      </div>
    </li>
  </ul>
</li>